#!/bin/bash

if [ "$1" == "" ]; then
	echo "Missing parameter for ip. Please specify the ip"
	echo "Syntax: ./ipsweep 192.168.0"

else
	for ip in $(seq 1 254); do
		ping -c 1 $1.$ip | grep "64 bytes" | cut -d " " -f 4 | tr -d ":" &
	done
	echo 
fi

